### PR TITLE
Robots

### LINKED ISSUE #5: AI robots
- [x] AI robot pathing
- [x] Player robot inventory
- [ ] AI robot actions (tilling, planting, watering, fertilising, harvesting)
- [x] AI robot charge
- [x] AI robot upgrades
- [x] refill station

### LINKED ISSUE #20: Energy Station rework
Energy Station now has a maximum capacity and base regen rate that can be upgraded. When robots enter the radius of the energy station and need to recharge, they will refill to max and deduct the energy taken from the station. If no energy is available from the station the robot stops.

### PR DESCRIPTION
**Pull request by AdithaD**
A large feature that implements robots, some buildings into the game, and lots of UI to support robot configuration.

- Robot pathing and path selection GUI
- AI robot actions implemented. Robots for planting, watering, fertilising and harvesting. Did not implement tilling robot.
- Added batteries to the robots that they consume when moving and doing actions. They will power down if their batteries run out
- Add upgrades for the robots in form of items that can be attached to the robots
- Added a Energy station to manage robots. Configure robot paths, upgrades and identify robots from this block. Pick up and put down robots using F key to change energy stations. Energy stations also charge robots nearby and have an internal battery that is recharged over time
- Added a deposit box that acts as an inventory that players and robots can interact with.

### CODE REVIEW

**Comment by kenguin3535** [comment]
- Harvest doesnt work (does not increase in inventory)
- Quest doesnt work (can't submit even though there is 50)
- game crash on picking up robot (to do with energy station?) and walking around pressing f
- can place upgrades on different robots without closing the tab?
- water robot does not run out of power and runs infinitely off screen if you push it while constantly draining energy 
- path setting feels really slow and does not respond half the time
- can walk while setting robot path causing you to never be able to clear screen
- you can still move after pressing tab, causing the screen to move while the character is frozen

**Comment by AdithaD** [comment]
Thanks for the feedback, I've fixed those points. Please test again.

**Comment by kenguin3535** [comment]
I cant open any menu please fix urgent

**Comment by kenguin3535** [comment]
-cant open any menu before interacting with robot menu
-water robot does not automatically recharge when out of battery even in power station area (might be to do with battery)
-upgrades disappear when picking up robots? can pick up 2 robots at once

**Comment by kenguin3535** [comment]
-deposit box works :)
-inventory does not display on phone screen (tab) (purely visual we still have the items)
-"add from inventory" should change to "back" after clicking it to be more intuitive
-***crash on pressing any robot in robot menu
-is selling ui change intentional? can't sell one by one now?
-water drains over time as long as you haven't harvested crop
-waterer stops working after a while(? around 3 minutes 6 crops in)
-fertiliser doesn't appear to work at all?

**Comment by AdithaD** [comment]
water cant be refilled as of right now. that's definitely an oversight. the other issues have been fixed however.

**Comment by kenguin3535** [comment]
-pressing buy until <109 causes you to spend money but get nothing
-error "Invalid type in function 'give_robot_energy' in base 'Node2D (EnergyStation)'. The Object-derived class of argument 1 (previously freed) is not a subclass of the expected argument class." when taking water robot?
-robot pathing doesn't work and crashes game after a bit
-water works (can refill and spend water)

**Comment by kenguin3535** [comment]
-still does not give items when buying over 100 while taking your money what a scam
-im assuming water station stops refilling after a bit otherwise that is bugged
-when using another energy station, it still displays the last robot you have modified even though it may not be connected to the station

**Comment by kenguin3535** [comment]
-after hitting inventory cap =100, store still allows you to spend coins for nothing
-after place the water robot next to water station, the water station stops refilling even though the robot is not taking the water, and the water station does not return to refilling even after water robot is removed after

**Review by kenguin3535 — COMMENTED** [review]
In my 100% certified expert opinion I think we are good to proceed

**Review by kenguin3535 — APPROVED** [review]

**Pull request merged**
